### ISSUE TITLE
我自己搭建到openshift上了，但是发现不支持内嵌html语法

### ISSUE THREAD

**Issue by mirage1993** [geekcompany/DeerResume#11]
用html内嵌图片后可以实时预览到图片，但是保存后去首页看的话还是没有图片。导出PDF也没有

**Comment by ethe** [comment]
确实，这个不支持html标签

**Comment by easychen** [comment]
出于（在线多用户版本的）安全考虑，特地去掉了HTML支持。但其实简单修改下就可以支持了。
有兴趣的同学可以自己改下。
输出在
https://github.com/geekcompany/DeerResume/blob/master/resume.html#L7
修改方式可以stackoverflow
http://stackoverflow.com/questions/9381926/insert-html-into-view-using-angularjs
