### ISSUE TITLE
一些让我不愿意使用它的理由

### ISSUE THREAD

**Issue by luckytianyiyan** [geekcompany/DeerResume#12]
# 我是早上在知乎上看到的，然后不暇思索就使用了。

# 晚上回来我看代码才发现问题。

1. **为什么默认将数据上传到你的SAE上？而且在没有任何告知的情况下这么做。**

	在部署说明上只字未提。我不愿猜测你这么做的想法。
	
	我只觉得，至少应该默认用 `data.php` , 也就是你所谓的静态(**动态的语言干静态的活儿**).

2. 服务器代码没有开源，光有这个壳子有什么用？

	我可以假设这是为了让部署变得简单。但是...这充其量就是一个简单的网页模板。

3. 密码用Get方式明文传输，然后reload了一把。客户端没有对其摘要。

   我很纳闷，是水平低还是故意为之？
   
   首先，你我都知道简历含着很多隐私信息。
   
   其次，哪怕是新手，都知道密码必须POST方式，再者，以现在这个态度，我感觉，你的数据库存放密码的时候未必摘要过。
   
   糟糕的猜测就是，你能拿到使用者的邮箱、密码、简历。虽然简历之后可以删掉保存，但是只要缓存一份，用户根本抹不掉。这就提升到道德问题了不是吗？

**Comment by easychen** [comment]
关于第一个问题，请认真查看「部署指南」中第三段，我做了明确说明：

「 为了将易用性做到最好，我们使用了云服务来做数据可控性和转换PDF，如果您对此不放心，可以在下载完PDF后，手动清空简历数据。」

然后我也提供了可以独立部署的方式（见FAQ段）。使用SAE做数据缓存只有一个原因，保证只能存放静态页面的环境，比如GitHub Page，可以轻松使用。

关于第二个问题，data.php已经实现了服务器端的接口，只是不支持多用户而已。

关于第三个问题，如果你认真看过上边那段说明，就清楚DeerResume最初的设计目的本来是提供一个Draft环境，在线编辑简历并生成PDF。阅读密码和管理密码都是后来衍生的需求，顺手加的。不入您法眼的话，您大可以自行实现。

当这部分需求越来越多以后，我们开发了一个完整的在线Markdown简历服务，http://www.deercv.com 。直接使用微信账户体系，不会存在任何密码泄露的问题。

DeerResume作为一个开源软件，我提供了代码实现，并在部署文档中有专门提示，您自己不看部署说明，（当然，更不用说代码了），反而对提供方的意图乱加猜测，这是在知乎养成的好习惯么？
