### ISSUE TITLE
简历不能查看，显示数据库错误了。。。。

### ISSUE THREAD

**Issue by Nsir15** [geekcompany/DeerResume#32]
大神，是不是最近没在更新了，我的简历现在没法继续编辑了。。。。

**Comment by easychen** [comment]
deercv 之前就宣布停止运营了（登录用公众号不在我这里了），可以告诉我二级域名，我会将简历内容发给你。

**Comment by Nsir15** [comment]
好的，多谢大神了。我的域名 是 ： http://nanxi.deercv.com/   。这个发的是PDF 还是 Markdown的原稿
