### ISSUE TITLE
麻烦了

### ISSUE THREAD

**Issue by hocgin** [geekcompany/DeerResume#34]
@easychen 

能帮忙把我的.md发给我吗 我原来的是 hocgin.deercv.com

麻烦了

**Comment by hocgin** [comment]
我原先有使用过静态的 地址是: https://github.com/vita-hocgin/vita-hocgin.github.io
使用的域名是: http://vita.hocg.in/ 麻烦了

**Comment by easychen** [comment]
hocgin 这个二级域名下只有一个java的默认模板，里边不包含联系方式。

**Comment by starlightme** [comment]
同求发下，O(∩_∩)O谢谢  http://jimmy66.deercv.com/
