### ISSUE TITLE
管理密码设置无效

### ISSUE THREAD

**Issue by huangyafei** [geekcompany/DeerResume#5]
你好，管理密码设置后是无效的，任何人依然可以直接进入管理页面。

**Comment by jacezq** [comment]
设置管理密码后无效，怎么解决的

**Comment by jacezq** [comment]
额，不能只给有管理密码的人才能进入后台么，预览的人只能预览

**Comment by jacezq** [comment]
我知道了，这个是能进入后台，但是保存的时候会验证管理密码，不对的话不能修改
